---
- name: Check if daemonize is installed.
  command: which daemonize
  changed_when: false
  failed_when: false
  register: daemonize_installed

- name: Download daemonize source
  get_url:
    url: "https://github.com/bmc/daemonize/archive/release-{{ daemonize_version }}.tar.gz"
    dest: "/tmp/daemonize-{{ daemonize_version }}.tar.gz"
  when: daemonize_installed|failed

- name: Expand daemonize source
  command: >
    tar -zxf /tmp/daemonize-{{ daemonize_version }}.tar.gz
    chdir=/tmp
    creates=/tmp/daemonize-release-{{ daemonize_version }}/INSTALL
  when: daemonize_installed|failed

- name: Compile daemonize
  command: >
    {{ item }}
    chdir=/tmp/daemonize-release-{{ daemonize_version }}
  when: daemonize_installed|failed
  with_items:
    - ./configure
    - "make prefix={{ daemonize_install_path }}"
    - "make prefix={{ daemonize_install_path }} install"
