---
- name: Uninstall deprecated packages or ones we don't want anymore
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - phpunit

- name: Install necessary packages for proper system state
  apt: name={{ item }} state=latest
  with_items:
    - sysv-rc-conf
    - python-apt
    - python-pycurl
    - python-mysqldb
    - gcc
    - git
    - curl
    - unzip
    - php5-mysql
    - traceroute
    - ack-grep
    - subversion
    - autojump
    - siege

- name: Get Composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755 validate_certs=no

- name: Install PsySH
  get_url: url=http://psysh.org/psysh dest=/usr/local/bin/psysh mode=0755

- name: Install Boris
  get_url: url=https://github.com/d11wtq/boris/releases/download/v1.0.8/boris.phar dest=/usr/local/bin/boris mode=0755 validate_certs=no

- name: Set up host entries
  lineinfile: dest=/etc/hosts line="127.0.0.1 hhvm.hgv.dev php.hgv.dev cache.php.hgv.dev cache.hhvm.hgv.dev admin.hgv.dev"

- name: Get PHPUnit
  get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit mode=0755 validate_certs=no

- name: Install CodeCeption test suite
  get_url:
    url: http://codeception.com/codecept.phar
    dest: /usr/local/bin/codecept
    mode: 0755

- name: Create custom config directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ usr_config }}"
    - "{{ usr_config_sites }}"
    - "{{ usr_config_provision }}"

- include: swap.yml
- include: daemonize.yml
